services:
  postgres:
    container_name: orm_postgres
    image: postgis/postgis:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ns5200ST34b
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: