services:
  postgres:
    container_name: orm_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ns5200ST34b
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data


  schemaspy:
    container_name: schema_spy
    image: schemaspy/schemaspy:latest
    depends_on:
      - postgres
    environment:
     -t: pgsql
     -host: orm_postgres
     -db: postgres
     -u: postgres
     -p: Ns5200ST34b
    volumes:
      - ./schemaspy_output:/output
    ports:
      - '8080:8080'

volumes:
  pgdata: