services:
  postgres:
    container_name: hoge_postgres
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: hoge
      POSTGRES_USER: hoge
      POSTGRES_PASSWORD: hoge
    ports:
      - '5432:5432'
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  schemaspy:
    container_name: schema_spy
    image: schemaspy/schemaspy:latest
    environment:
      -t: pgsql
      -host: hoge_postgres
      -db: hoge
      -u: hoge
      -p: hoge
    volumes:
      - ./schemaspy/output:/output
    ports:
      - '8080:8080'